Protect sign_certificate endpoint using basic auth
alphagov/notifications-certificate-management pull request #11
Opened 2021-01-19 12:38 UTC by klssmith

We want to protect the sign_certificate endpoint using basic
authentication. Each MNO will have a username and password.

In a later PR we can then use the basic auth username to check that MNOs
can only issue a CSR for one of their own certificates.

2021-01-19 14:19 UTC, rjbaker requested changes
Looks great 👍  One comment re password comparison.

2021-01-19 14:19 UTC, rjbaker commented on main.py
> +    if username in credentials and credentials[username] == password:
Not that it matters too much for this app, but passwords should be checked using constant-time comparison. E.g. https://sqreen.github.io/DevelopersSecurityBestPractices/timing-attack/python

2021-01-19 14:46 UTC, klssmith commented on main.py
> +    if username in credentials and credentials[username] == password:
Thanks, I hadn't noticed that. I've updated the code to use `hmac.compare_digest` and rebased the change into the existing commit.

2021-01-19 15:06 UTC, klssmith commented
I've just realised that we might not be able to merge this PR - the app will now expect all the basic auth usernames and passwords to be there when it starts and I don't think we have those set up yet. Do I need to rewrite things so that those environment variables are optional for now?

2021-01-20 11:47 UTC, klssmith commented
@rjbaker I've added a new commit to make the environment variables optional for now. If we have them all already, I can just delete the commit

2021-01-21 10:57 UTC, klssmith commented
This will need the basic auth usernames and passwords to exist before it is merged - the code expects those environment variables to be there on startup

2021-01-25 10:58 UTC, merged